name: Syncthing Discovery
version: 0.0.2
slug: syncthing-discovery
description: Syncthing Discovery server for Home Assistant
url: "https://github.com/BartRuSec/syncthing-utils-ha-addons/tree/main/syncthing-discovery"
image: "ghcr.io/bartrusec/syncthing-utils-ha-addons-syncthing-discovery-{arch}"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
init: false
startup: services
ports:
  22843/tcp: 22843
ports_description:
  22843/tcp: Syncthing Discovery port
map:
  - ssl:rw
options:
  certfile: fullchain.pem
  keyfile: privkey.pem
schema:
  certfile: str
  keyfile: str
